################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
---
apiVersion: v1
data:
  args: '--character-set-server=utf8mb4 --collation-server=utf8mb4_bin --explicit-defaults-for-timestamp=1 --datadir=/var/lib/mysql/data'
kind: ConfigMap
metadata:
  name: mysql-args
---
apiVersion: v1
data:
  init.sql: grant all privileges on *.* to xwiki@'%'
kind: ConfigMap
metadata:
  name: mysql-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - 
        args:
        - $(MYSQL_ARG)
        env:
        - 
          name: MYSQL_ARG
          valueFrom:
            configMapKeyRef:
              key: args
              name: mysql-args
        - 
          name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: mysql
        - 
          name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql
        - 
          name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mysql
        - 
          name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql
        image: mysql:5.7
        name: mysql
        ports:
        - 
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - 
          mountPath: /var/lib/mysql
          name: mysql
        - 
          mountPath: /docker-entrypoint-initdb.d
          name: mysql-init
      volumes:
      - 
        name: mysql
        persistentVolumeClaim:
          claimName: mysql
      - 
        configMap:
          name: mysql-init
        name: mysql-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xwiki
spec:
  selector:
    matchLabels:
      app: xwiki
  template:
    metadata:
      labels:
        app: xwiki
    spec:
      containers:
      - 
        env:
        - 
          name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: DB_DATABASE
              name: xwiki
        - 
          name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: xwiki
        - 
          name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: xwiki
        - 
          name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: xwiki
        image: academiaonline/xwiki-docker:latest
        imagePullPolicy: Always
        name: xwiki
        ports:
        - 
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - 
          mountPath: /usr/local/xwiki          
          name: xwiki
      volumes:
      - 
        name: xwiki
        persistentVolumeClaim:
          claimName: xwiki
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql
spec:
  ingress:
  - 
    from:
    - 
      podSelector:
        matchLabels:
          app: xwiki
    ports:
    - 
      port: 3306
      protocol: TCP
  podSelector:
    matchLabels:
      app: mysql
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: xwiki
spec:
  ingress:
  - 
    ports:
    - 
      port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: xwiki
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xwiki
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/xwiki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
stringData:
  MYSQL_DATABASE: xwiki
  MYSQL_PASSWORD: xwwiki
  MYSQL_ROOT_PASSWORD: xwiki
  MYSQL_USER: xwiki
kind: Secret
metadata:
  name: mysql
type: Opaque
---
apiVersion: v1
stringData:
  DB_DATABASE: xwiki
  DB_HOST: mysql
  DB_PASSWORD: xwiki
  DB_USER: xwiki
kind: Secret
metadata:
  name: xwiki
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - 
    port: 3306
    protocol: TCP
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: xwiki
spec:
  ports:
  - 
    nodePort: 30000
    port: 8080
    protocol: TCP
  selector:
    app: xwiki
  type: NodePort
---
