################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
networks:
  mysql:
    internal: true
  xwiki:
    internal: false
services:
  mysql:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    environment:
    - MYSQL_ROOT_PASSWORD=/etc/mysql/xwiki-db-root-password
    - MYSQL_USER_FILE=/etc/mysql/xwiki-db-username
    - MYSQL_PASSWORD_FILE=/etc/mysql/xwiki-db-password
    - MYSQL_DATABASE=xwiki
    
    TO BE CONTINUED...
    
    image: mysql:5.7
    networks:
    - mysql
  xwiki:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    image: academiaonline/xwiki-docker:latest
    networks:
    - mysql
    - xwiki
    ports:
    - 30000:8080
version: '3.8'
